version: '3.5'

services:
  service:
    container_name: navy_plan_service
    image: navy/plan/service
    environment:
      PG_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=navy_testplan;Username=navy;Password=navy;Pooling=true;Maximum Pool Size=100"
    ports:
      - "81:80"
      - "444:443"
  client:
    container_name: navy_plan_client
    image: navy/plan/client
    ports:
      - "80:80"
      - "443:443"